server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848         #Nacos服务注册中心地址
    sentinel:
      transport:
        dashboard: localhost:8080 #配置Sentinel dashboard控制台服务地址
        port: 8719 #默认8719端口，假如被占用会自动从8719开始依次+1扫描,直至找到未被占用的端口
      web-context-unify: false # controller层的方法对service层调用不认为是同一个根链路
      #添加Nacos数据源配置
      datasource:
        ds1:   #就是自定义key，也可以叫做限流类型等等
          nacos:
            server-addr: localhost:8848  #nacos地址
            #就nacos配置里面的
            dataId: ${spring.application.name}
            groupId: DEFAULT_GROUP
            data-type: json
            #规则 RuleType枚举类查看
              #flow、degrade、param-flow、system、authority、gw-flow、gw-api-group
            #流控(流量控制)规则：flow
            rule-type: flow # com.alibaba.cloud.sentinel.datasource.RuleType
            #熔断降级规则：degrade
            #热点规则：param-flow
            #系统保护规则：system
            #访问控制规则：authority